"""
Pydantic validation layer. Every proposal generated by the matcher must
pass through here before it is writable to the CRM or shown in the
review app. This is the "last line of defense before changes affect
production systems" piece — kept deliberately separate from matching
logic so it can be reasoned about (and demoed) on its own.
"""
from pydantic import BaseModel, field_validator, model_validator
from typing import Literal, Optional
from .config import STATUS_VALUES

ClassificationType = Literal[
    "no_change", "needs_fix", "no_account_yet",
    "vanished_from_website", "misparented", "duplicate",
]


class ProposedChange(BaseModel):
    proposal_id: str
    account_id: Optional[str] = None          # None only for "no_account_yet" creates
    classification: ClassificationType
    evidence: str                              # what the matcher matched on — shown in review app
    fields: dict = {}                           # field -> new value
    note: str = ""

    @field_validator("evidence")
    @classmethod
    def evidence_required(cls, v):
        if not v or not v.strip():
            raise ValueError("evidence must not be empty — reviewer needs a reason to approve")
        return v

    @field_validator("fields")
    @classmethod
    def status_must_be_valid(cls, v):
        if "status" in v and v["status"] not in STATUS_VALUES:
            raise ValueError(f"status must be one of {STATUS_VALUES}, got {v['status']!r}")
        return v

    @model_validator(mode="after")
    def duplicate_requires_target(self):
        if self.classification == "duplicate" and "duplicate_of_account" not in self.fields:
            raise ValueError("duplicate classification requires fields.duplicate_of_account")
        return self

    @model_validator(mode="after")
    def account_id_required_unless_new(self):
        if self.classification != "no_account_yet" and not self.account_id:
            raise ValueError("account_id is required for all classifications except no_account_yet")
        return self
